In [1]:
#NAME: MANNEMELA SAI SRITHAJA
#REGISTER NUMBER:31 2221 5002 056
#DEPARTMENT: IT-A
#ASSIGNMENT PROBLEM : TEACHING AND LEARNING ALGORITHM 

In [2]:
import numpy as np   

In [3]:
def griewank(x):
    D = len(x)
    sum_sq = np.sum(x**2)     #function to find the fitness value
    prod_cos = np.prod(np.cos(x / np.sqrt(np.arange(1, D+1))))
    return 1 + (1/4000)*sum_sq - prod_cos

In [4]:
def initialize_population(population_size, problem_size, lower_bound, upper_bound):  #generating a random population
    return np.random.uniform(lower_bound, upper_bound, (population_size, problem_size))

In [5]:
def generate_random_pairs(population_size):
    return np.random.randint(0, population_size, population_size) #generation random learner-influencer pairs

In [6]:
def learner_phase(population, pairs, r):
    for p, q in enumerate(pairs):
        for j in range(population.shape[1]):        #learner phase
            old_value_p = population[p, j]
            old_value_q = population[q, j]          #updating the value impacted by the peer
            diff = r * (old_value_p - old_value_q)
            population[p, j] = old_value_p + diff

In [7]:
population_size = 6
problem_size = 5        #initializing parameters for number of subjects and learners
lower_bound = -600      #initializing lower bound and upper bound values 
upper_bound = 600
max_iter = 10000        #number of iterations teh function will run 

In [8]:
population = initialize_population(population_size, problem_size, lower_bound, upper_bound)
fitness_values = np.array([griewank(individual) for individual in population])  #finding fitness values for each learner
print("The initial population:",population)  
print("The fitness value of initial population:",fitness_values)

The initial population: [[-282.53708986 -339.30721587 -390.67992675 -556.44721993 -317.61959001]
 [-357.22388215 -580.87791888   97.35366034 -332.21599409  113.69791461]
 [ 286.92301564  419.26974476 -239.26854115   97.43151527  434.58887328]
 [-530.97209859  155.83566259  475.75315916 -591.35535302  323.52626293]
 [-251.32619371  -12.10994034  290.82662496 -148.60208639  284.56611512]
 [-292.65662308   15.12999136  380.63785253 -585.61380349  -99.80431084]]
The fitness value of initial population: [190.47923222 150.14455537 129.4343293  247.92075776  63.73936563
 147.079745  ]


In [9]:
best_solution = None
best_fitness = np.inf                       #finding best solution and best fitness value
min_index = np.argmin(fitness_values)
if fitness_values[min_index] < best_fitness:
    best_solution = population[min_index]
    best_fitness = fitness_values[min_index]
print(best_fitness)

63.73936563186711


In [10]:
for i in range(10000):
    subject_mean= np.mean(population, axis=0)  #taking mean for each subject
    r_j_i=np.random.uniform(0, 1, (5))          #random number initialization

    for i in range(population_size):
        
        Tf = round(1 + np.random.rand() * 2 - 1)
        diff_mean =(r_j_i*(best_solution-(Tf *subject_mean)))  #finding difference mean
        
        new_solution = population[i] + diff_mean        #using difference mean updating the population
        new_fitness = griewank(new_solution)            #finding fitness for new solution

        if new_fitness < fitness_values[i]:         
            population[i] = new_solution            #updating population only if fitness value is reduced
            fitness_values[i] = new_fitness

        if new_fitness < best_fitness:
            best_solution = new_solution      #updating the best solution and fitness for new population
            best_fitness = new_fitness
    learner_influencer_pairs = generate_random_pairs(population_size)
    r = np.random.rand()  # Random number for subject j
    learner_phase(population, learner_influencer_pairs, r)

c:\Users\nadhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\nadhi\AppData\Local\Temp\ipykernel_9104\2061203398.py:3: RuntimeWarning: overflow encountered in square
  sum_sq = np.sum(x**2)     #function to find the fitness value
C:\Users\nadhi\AppData\Local\Temp\ipykernel_9104\2390327412.py:6: RuntimeWarning: overflow encountered in scalar subtract
  diff = r * (old_value_p - old_value_q)
C:\Users\nadhi\AppData\Local\Temp\ipykernel_9104\2061203398.py:4: RuntimeWarning: invalid value encountered in cos
  prod_cos = np.prod(np.cos(x / np.sqrt(np.arange(1, D+1))))
C:\Users\nadhi\AppData\Local\Temp\ipykernel_9104\3535123031.py:8: RuntimeWarning: invalid value encountered in multiply
  diff_mean =(r_j_i*(best_solution-(Tf *subject_mean)))  #finding difference mean
C:\Users\nadhi\AppData\Local\Temp\ipykernel_9104\3535123031.py:10: Runtim

In [11]:
print("The updated fitness value:",fitness_values)   #the fitness values and best fitness after optimization using teaching&learning based optimization
print("The best fitness value after 10000 iterations:",best_fitness)

The updated fitness value: [146.5647405  140.43519033 129.4343293  247.92075776  63.73936563
 147.02586902]
The best fitness value after 10000 iterations: 63.73936563186711
